"""add date and time fields to tasks

Revision ID: 72903bec5395
Revises: 
Create Date: 2026-04-15 12:48:37.092626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72903bec5395'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_date', sa.Date(), nullable=True))
    op.add_column('tasks', sa.Column('start_time', sa.String(length=5), nullable=True))
    op.add_column('tasks', sa.Column('end_time', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'end_time')
    op.drop_column('tasks', 'start_time')
    op.drop_column('tasks', 'task_date')
    # ### end Alembic commands ###
